widget improvements
AmrDeveloper/LinkHub pull request #33
Opened 2023-02-18 16:45 UTC by SIRSteiner

2023-02-18 20:59 UTC, SIRSteiner commented
![IMG_20230218_215421](https://user-images.githubusercontent.com/3488638/219899139-4789b1b5-421f-4d99-848d-1ee34bf88663.jpg)
Smallest widget and a bigger

![IMG_20230218_215641](https://user-images.githubusercontent.com/3488638/219899213-7e5b6b6f-233d-43f5-9035-f3254cb67af1.jpg)
New icon for none folder

2023-02-19 09:01 UTC, AmrDeveloper requested changes

2023-02-19 09:01 UTC, AmrDeveloper commented on app/src/main/res/values-de/strings.xml
> +    <string name="none">- keiner -</string>
I think it butter to not using - - so to be like other languages

2023-02-19 09:01 UTC, AmrDeveloper commented on app/src/main/res/layout/widget_item_link.xml
> +    android:theme="@style/ThemeOverlay.LinkHub.AppWidgetContainer"
For now it better to keep the background white to be similar to app white theme, maybe then we can try to support multi themes

2023-02-19 09:02 UTC, AmrDeveloper commented
Note that it will be much easier for your to make each PR on a new branch so you can submit each one without waiting for the other to be merged for example

2023-02-19 09:03 UTC, AmrDeveloper commented on app/src/main/res/drawable/ic_directory_none.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Nice idea for none folder icon

2023-02-19 09:35 UTC, SIRSteiner commented on app/src/main/res/values-de/strings.xml
> +    <string name="none">- keiner -</string>
I will change it with the next commit

2023-02-19 09:46 UTC, SIRSteiner commented on app/src/main/res/layout/widget_item_link.xml
> +    android:theme="@style/ThemeOverlay.LinkHub.AppWidgetContainer"
At the moment (latest official release) background depends on system design and also with that commit, that's not changed. But the (theme) text color for the widget in dark mode is only applying with that line.
![IMG_20230219_103339](https://user-images.githubusercontent.com/3488638/219940554-6be093d8-40c5-4d15-8dab-8bd0ec94c1c3.jpg)
System light mode with commit

You can see light mode works at the widget.

2023-02-19 10:55 UTC, AmrDeveloper commented on app/src/main/res/layout/widget_item_link.xml
> +    android:theme="@style/ThemeOverlay.LinkHub.AppWidgetContainer"
You are right, great work 👍🏻

2023-02-19 10:56 UTC, AmrDeveloper requested changes

2023-02-19 10:56 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/data/Folder.kt
> +    @ColumnInfo(name = "color_name", defaultValue = "BLUE") var folderColor: FolderColor = FolderColor.NONE,
We need to change the default value in column info to match the Folder NONE so it should be `NONE`

2023-02-19 11:31 UTC, SIRSteiner commented on app/src/main/java/com/amrdeveloper/linkhub/data/Folder.kt
> +    @ColumnInfo(name = "color_name", defaultValue = "BLUE") var folderColor: FolderColor = FolderColor.NONE,
I don't know why but when I change this as suggested the app doesn't show any links nor folder and you can't add any link/folder.

2023-02-19 14:16 UTC, SIRSteiner commented
I splitted these commits and made separate push requests as advised

2023-02-19 14:16 UTC, closed without merging

2023-02-19 15:22 UTC, AmrDeveloper commented
@SIRSteiner The problem is that we changed the DB Schema because we changed defaultValue I will check other PR first then we can think of solution or removing default value if it un needed