Added import/export to html functionality
AmrDeveloper/LinkHub pull request #54
Opened 2024-03-20 11:01 UTC by GalievBulat

I've made the requested functionality, while preserving the original code style. I've made the import/export setting close to the import/export setting of json files functionality. Feel free to make changes to the code/design.

2024-03-20 20:12 UTC, AmrDeveloper requested changes

2024-03-20 20:12 UTC, AmrDeveloper commented
Hello @GalievBulat,

The code looks great for me but we need to make the design more simpler so we can add more extension on the same view

2024-03-24 05:32 UTC, GalievBulat commented
@AmrDeveloper yes, I see your point: I think it would be a better decision to implement the functionality on the single fragment, and then change the type of import/export, according to the user's preferences

2024-03-24 05:33 UTC, GalievBulat commented
I think using a dialog with spinner of which type of file to import/export would be a good design?

2024-03-24 07:25 UTC, GalievBulat commented
@AmrDeveloper in new commit I've moved import/export functionality into a single abstract Parser class, so check it out, please

2024-03-25 11:15 UTC, AmrDeveloper requested changes

2024-03-25 11:15 UTC, AmrDeveloper commented on app/src/main/res/layout/fragment_setting.xml
> +        <TextView
The code is good, so we need to think of simple UI that can be used for many data formats,

- One option is to show a popup when click on import or export in ImportExportFragment to select type

- Spinner in ImportExportFragment to select type

2024-03-25 11:15 UTC, AmrDeveloper commented on app/src/main/res/layout/fragment_setting.xml
> +        <View
My point to this design is that Settings Screen should not care about the details of ImportExport screen how many types....

2024-03-25 11:15 UTC, AmrDeveloper commented on app/src/main/res/navigation/nav_graph.xml
> +        tools:layout="@layout/fragment_import_export" >
After changing the ImportExportFragment to have UI component to select type we don't need arguments we send the type to the viewmodel and it will return data

2024-03-25 13:28 UTC, GalievBulat commented
@AmrDeveloper thank you, I think the requested changes are important to do: so I've made a file type picking dialog on an ImportExportFragment. So when user clicks import/export he first needs to pick a file type first

2024-03-26 20:26 UTC, AmrDeveloper requested changes

2024-03-26 20:26 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/data/ImportExportFileType.kt
> +
Please remove empty line

2024-03-26 20:26 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/data/source/local/FolderLocalDataSource.kt
> +    override suspend fun getFolderByName(name : String): Result<Folder> = withContext(ioDispatcher) {
Add new line before method declaration

2024-03-26 20:26 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/ui/importexport/ImportExportFragment.kt
> +            context?.let {  ImportExportFileTypePickerDialog.launch(it) { fileType ->
Please format the code

```kt
context?.let {  
    ImportExportFileTypePickerDialog.launch(it) { fileType ->
        importExportViewModel.setFileType(fileType)
        importDataFile()
    }
}
```

2024-03-26 20:26 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/ui/importexport/ImportExportViewModel.kt
> +    private var importExportFileParser: ImportExportFileParser = JsonImportExportFileParser()
We don't need to create instance of JsonImportExportFileParser then depending on type we create another parser instance so lets pass FileType to import and export functions and use the correct parser for this type

It will make code simpler and save memory

2024-03-26 20:26 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/ui/importexport/ImportExportViewModel.kt
> +            importExportFileParser.getFileType().extension
Remove those variables and pass the selected FileType to the place we need it

2024-03-26 20:26 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/ui/importexport/ImportExportViewModel.kt
> +    fun setFileType(fileType: ImportExportFileType){
Remove this function and pass the FileType directly to import / export functions

2024-03-26 20:29 UTC, AmrDeveloper commented
> @AmrDeveloper thank you, I think the requested changes are important to do: so I've made a file type picking dialog on an ImportExportFragment. So when user clicks import/export he first needs to pick a file type first

Thank you for update, there are some design points and feel free to discuss your idea and suggestion

My point is that import and export functions on view model should take the type and do their work, later they will pass this type to factory for example

```
val parser = FileParserFactory.getInstance(fileType)
parser.import() or parser.export()
```

The view model will not know which parser it used and don't save the file type

2024-03-26 20:30 UTC, AmrDeveloper commented on app/src/main/res/layout/fragment_setting.xml
> +        <TextView
You are right, thank you

2024-03-27 09:34 UTC, GalievBulat commented
@AmrDeveloper thanks for the suggested changes: I've change the code according to them, so please review the commit

2024-03-27 10:35 UTC, AmrDeveloper requested changes

2024-03-27 10:35 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/ui/importexport/ImportExportViewModel.kt
> +    private var importExportFileType: ImportExportFileType? = null
Now we don't need this variable

2024-03-27 10:35 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/util/ImportExportFileTypePickerDialog.kt
> +}
We can move this to a function in ImportExport settings because it's only needed their `launchImportExportFileTypePicker`

2024-03-27 10:35 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/data/parser/ImportExportFileParser.kt
> +    }
You can create the factory pattern but as a single function in the view model for now

```kt
fun getDataParser(fileType: ImportExportFileType): ImportExportFileParser {
    return when (fileType) {
        ImportExportFileType.JSON -> JsonImportExportFileParser()
        ImportExportFileType.HTML -> HtmlImportExportFileParser()
     }
}
```

2024-03-27 10:35 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/ui/importexport/ImportExportFragment.kt
> +            context?.let {
After converting this picker to function you can use `requireContext()` it will return non nullable context to you to use directly

2024-03-27 10:35 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/ui/importexport/ImportExportFragment.kt
> +    private var importExportFileType: ImportExportFileType? = null
Can be remove this variable and pass the state between functions?

2024-03-27 10:36 UTC, AmrDeveloper commented
Thank you @GalievBulat for changes, i have a little changes in places and file structure and everything else is good for me,

2024-03-27 11:47 UTC, GalievBulat commented on app/src/main/java/com/amrdeveloper/linkhub/ui/importexport/ImportExportFragment.kt
> +    private var importExportFileType: ImportExportFileType? = null
I think there the state of importExportFileType cannot be omitted because registerForActivityResult should be declared before they fragment is created, so i thing we cannot pass the state between functions

2024-03-27 12:24 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/ui/importexport/ImportExportFragment.kt
> +    private var importExportFileType: ImportExportFileType? = null
Okey lets keep it for now

2024-03-27 12:31 UTC, GalievBulat commented
I've made the requested changes, so please check once again

2024-03-27 20:23 UTC, AmrDeveloper approved these changes

2024-03-27 20:23 UTC, AmrDeveloper commented
Thank you for great work @GalievBulat

2024-03-27 20:23 UTC, merged