created remember the last used folder option
AmrDeveloper/LinkHub pull request #57
Opened 2024-04-06 19:24 UTC by GalievBulat

Remember the last used folder when adding new link option

2024-04-06 19:39 UTC, GalievBulat commented
Hello @AmrDeveloper I've implemented the requested feature, so please check it out

2024-04-07 20:48 UTC, AmrDeveloper requested changes
For me everything is good, just need to make two small changes

2024-04-07 20:48 UTC, AmrDeveloper commented on app/src/main/res/values/strings.xml
> +    <string name="default_folder">Remember the last used folder as default one</string>
We need to find translations for other langs

2024-04-07 20:48 UTC, AmrDeveloper commented on app/src/main/java/com/amrdeveloper/linkhub/ui/setting/SettingFragment.kt
> +        // Setup Auto saving
Please, Fix this comment to be `// Setup default folder`

2024-04-08 09:21 UTC, GalievBulat commented on app/src/main/res/values/strings.xml
> +    <string name="default_folder">Remember the last used folder as default one</string>
So should I use google translate to translate this line to all the other languages?

2024-04-08 20:51 UTC, AmrDeveloper commented on app/src/main/res/values/strings.xml
> +    <string name="default_folder">Remember the last used folder as default one</string>
> So should I use google translate to translate this line to all the other languages?

For now yes, and can we make it shorter than `Remember the last used folder as default one`, hmmm maybe `Enable Remember Folder` or `Remember last folder` what do you think?

2024-04-08 21:57 UTC, AmrDeveloper commented on app/src/main/res/values/strings.xml
> +    <string name="default_folder">Remember the last used folder as default one</string>
Great let's go with it

2024-04-09 10:56 UTC, GalievBulat commented
Hello, @AmrDeveloper, I've resolved the commented changes . So please check it out

2024-04-09 21:11 UTC, AmrDeveloper approved these changes

2024-04-09 21:11 UTC, merged